language: csharp
solution: Sailthru/Sailthru.sln

jobs:
  include:
    - dotnet: 2.1.810
      env: DOTNET=2.1
    - dotnet: 3.1.402
      env: DOTNET=3.1
    - mono: latest
      env: DOTNET=mono
  allow_failures:
    - dotnet: 2.1.810
    - dotnet: 3.1.402
  fast_finish: true

install:
  - nuget restore Sailthru/Sailthru.sln
  - if [ "$DOTNET" = "mono" ]; then nuget install NUnit.Console -Version 3.12.0-beta1 -OutputDirectory testrunner; fi

script:
  - msbuild /noLogo /p:Configuration=Release Sailthru/Sailthru.sln
  - if [ "$DOTNET" = "mono" ]; then mono ./testrunner/NUnit.ConsoleRunner.3.12.0-beta1/tools/nunit3-console.exe ./Sailthru/Sailthru.Tests/bin/Release/net452/Sailthru.Tests.dll; fi
  - if [ "$DOTNET" != "mono" ]; then dotnet test --no-build -f "netcoreapp${DOTNET}" -c Release Sailthru/Sailthru.sln
