language: csharp
solution: Sailthru/Sailthru.sln

install:
  - nuget restore Sailthru/Sailthru.sln
  - msbuild /t:Restore Sailthru/Sailthru.sln
  - nuget install NUnit.Console -Version 3.12.0-beta1 -OutputDirectory testrunner

script:
  - msbuild /p:Configuration=Release Sailthru/Sailthru.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.12.0-beta1/tools/nunit3-console.exe ./Sailthru/Sailthru.Tests/bin/Release/Sailthru.Tests.dll
  - msbuild /t:Pack /p:Configuration=Release Sailthru/Sailthru/Sailthru.csproj
  - nuget setApiKey $NUGET_API_KEY -Verbosity quiet >/dev/null 2>&1
  - nuget push Sailthru/Sailthru/bin/Release/Sailthru.Client.*.nupkg

# before_deploy:
#   - nuget setApiKey $NUGET_API_KEY -Verbosity quiet >/dev/null 2>&1
#   - msbuild /t:Pack /p:Configuration=Release Sailthru/Sailthru/Sailthru.csproj
#
# deploy:
#   skip_cleanup: true
#   provider: script
#   on:
#     branch: master
#   script: nuget push Sailthru/Sailthru/bin/Release/Sailthru.Client.*.nupkg
